# Generated by Django 2.2.1 on 2019-05-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news_mirae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('date_tmp', models.TextField()),
                ('tokenized_doc', models.TextField(null=True)),
                ('tokenized_title', models.TextField(null=True)),
                ('section', models.TextField(default='미래에셋')),
            ],
        ),
    ]
