# Generated by Django 2.2.1 on 2019-05-21 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='news_mirae',
        ),
    ]
