# Generated by Django 2.2.1 on 2019-05-21 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_newsightdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsightDb',
        ),
    ]
