# Generated by Django 2.2.1 on 2019-05-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_newsightdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='total_db',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('date', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('date_tmp', models.BigIntegerField(blank=True, null=True)),
                ('tokenized_doc', models.TextField(blank=True, null=True)),
                ('tokenized_title', models.TextField(blank=True, null=True)),
                ('query', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='NewsightDb',
        ),
    ]
