# Generated by Django 2.2.1 on 2019-05-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_auto_20190521_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_db',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
