# Generated by Django 2.2.1 on 2019-05-21 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0008_auto_20190521_1814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TotalDb',
        ),
    ]
